apiVersion: v2
name: code-server
description: A Helm chart for deploying code-server, qdrant, and ollama
type: application
version: 0.4.0
appVersion: "1.0.0"
dependencies:
  # - name: code-server
  #   version: 4.103.1
  #   repository: https://helm.coder.com/v2
  - name: qdrant
    version: 1.16.0
    repository: https://qdrant.github.io/qdrant-helm
  - name: ollama
    version: 1.34.0
    repository: https://otwld.github.io/ollama-helm
