apiVersion: v2
name: jupyter
description: A Helm chart for Jupyter Notebook/Lab
type: application
version: 0.1.15
appVersion: "1.0.0"
maintainers:
  - name: Thomas Guyader
    url: "https://github.com/tom333"
    email: ""
