apiVersion: v1
kind: Service
metadata:
  name: {{ include "datalab.fullname" . }}-mlflow
  labels:
    {{- include "datalab.labels" . | nindent 4 }}
    app.kubernetes.io/component: mlflow
spec:
  type: {{ .Values.mlflow.service.type }}
  ports:
  - port: {{ .Values.mlflow.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "datalab.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mlflow
