apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datalab.fullname" . }}-mlflow-secret
  labels:
    {{- include "datalab.labels" . | nindent 4 }}
    app.kubernetes.io/component: mlflow
type: Opaque
stringData:
  aws-access-key-id: {{ .Values.mlflow.s3.accessKeyId | quote }}
  aws-secret-access-key: {{ .Values.mlflow.s3.secretAccessKey | quote }}
