apiVersion: v2
name: datalab
version: 1.0.34
dependencies:
  - name: mlflow
    version: 5.1.17
    repository: https://charts.bitnami.com/bitnami
  - name: minio
    version: 5.4.0
    repository: https://charts.min.io/
  - name: mysql
    version: 13.0.4
    repository: https://charts.bitnami.com/bitnami
  - name: zenml
    version: 0.91.1
    repository: oci://public.ecr.aws/zenml
