apiVersion: v2
name: datalab
version: 1.6.2
dependencies:
  - name: postgresql
    version: 16.7.27
    repository: https://charts.bitnami.com/bitnami
  - name: rustfs
    version: 0.0.81
    repository: https://charts.rustfs.com/
  # - name: mysql
  #   version: 13.0.4
  #   repository: https://charts.bitnami.com/bitnami
  # - name: zenml
  #   version: 0.93.1
  #   repository: oci://public.ecr.aws/zenml
