apiVersion: v2
name: datalab
version: 1.0.46
dependencies:
  - name: mlflow
    version: 1.8.1
    repository: https://community-charts.github.io/helm-charts
  # - name: minio
  #   version: 5.4.0
  #   repository: https://charts.min.io/
  # - name: mysql
  #   version: 13.0.4
  #   repository: https://charts.bitnami.com/bitnami
  # - name: zenml
  #   version: 0.91.2
  #   repository: oci://public.ecr.aws/zenml
