apiVersion: v2
name: datalab
version: 2.0.0
dependencies:
  - name: postgresql
    version: 18.4.0
    repository: https://charts.bitnami.com/bitnami
  - name: rustfs
    version: 0.0.83
    repository: https://charts.rustfs.com/
  # - name: mysql
  #   version: 13.0.4
  #   repository: https://charts.bitnami.com/bitnami
  # - name: zenml
  #   version: 0.93.1
  #   repository: oci://public.ecr.aws/zenml
